---
development:
  cloud_name: dat999xkb
  api_key: '284447624913469'
  api_secret: es22vnmqabWTvibjnkZNzQhaYqE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dat999xkb
  api_key: '284447624913469'
  api_secret: es22vnmqabWTvibjnkZNzQhaYqE
  enhance_image_tag: true
  static_image_support: true
# test:
#   cloud_name: dat999xkb
#   api_key: '284447624913469'
#   api_secret: es22vnmqabWTvibjnkZNzQhaYqE
#   enhance_image_tag: true
#   static_image_support: false
